global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "konect-backend"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/backend-active.json
        refresh_interval: 5s
