name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          OAUTH_GOOGLE_CLIENT_ID: dummy
          OAUTH_GOOGLE_CLIENT_SECRET: dummy

          OAUTH_NAVER_CLIENT_ID: dummy
          OAUTH_NAVER_CLIENT_SECRET: dummy

          OAUTH_KAKAO_CLIENT_ID: dummy
          OAUTH_KAKAO_CLIENT_SECRET: dummy

          SLACK_ERROR_WEBHOOK: dummy
        run: ./gradlew clean build -x test -Dspring.profiles.active=prod

      - name: Rename jar to app.jar
        run: |
          JAR_FILE=$(ls build/libs/*.jar | grep -v plain | head -n 1)
          cp "$JAR_FILE" build/libs/app.jar

      - name: Transfer app.jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "build/libs/app.jar"
          target: ${{ secrets.WORK_DIR }}
          rm: false

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Restarting konect service..."
            sudo systemctl restart konect
            echo "Checking service status..."
            sudo systemctl status konect --no-pager
            echo "Waiting for service to respond..."
            ready=0
            for i in {1..20}; do
                if curl -fsS http://localhost:8080/actuator/health | grep -q '"status":"UP"'; then
                echo "Service is up."
                ready=1
                break
              fi
              echo "Service not ready yet. Retrying..."
              sleep 3
            done
            if [ "$ready" -ne 1 ]; then
              echo "Service did not become ready in time."
              exit 1
            fi
            echo "Deployment completed"
